# Generated by Django 5.2.13 on 2026-04-28 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websitex_project", "0003_entries_delete_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entries",
            old_name="username",
            new_name="user",
        ),
    ]
