# Generated by Django 5.2.13 on 2026-04-28 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websitex_project", "0004_rename_username_entries_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entries",
            new_name="Entry",
        ),
    ]
